# Netlify Configuration for React Notes App with Vite

[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  # Let Netlify auto-detect the framework and proxy properly
  autoLaunch = false
  targetPort = 5173
  port = 8888
  # Remove custom command to let Netlify handle Vite properly
  
# API routes to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for production only - exclude common static file extensions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Only apply in production, not dev
  conditions = {Country = ["!dev"]}

[context.development.environment]
  NODE_ENV = "development"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache the main HTML file
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"